export const DATA = {
  name: 'Ayush Nema',
  role: 'Full Stack Developer',
  tagline: "I'm Ayush, a full stack developer building scalable web apps from 0 to 1.",
  about: 'MERN stack engineer specialising in real-time systems, scalable APIs, and intuitive interfaces. Currently interning at Techwalaa, Delhi.',
  email: 'nemaayush22@gmail.com',
  phone: '+91 9407004701',
  linkedin: 'https://www.linkedin.com/in/ayush-nema-58162830b/',
  github: 'https://github.com/Ayush-Nema1',
  location: 'Jabalpur, Madhya Pradesh, India',

  projects: [
    {
      id: 1,
      title: 'Social Media Web Application',
      desc: 'Scalable full-stack social media platform with Redux-based global state management, user discovery and connections, likes, comments, secure post CRUD operations, and PDF resume generation.',
      image: '/images/projects/p1.png',
      tags: ['Next.js', 'React.js', 'Redux Toolkit', 'Node.js', 'Express.js', 'MongoDB', 'JWT', 'Multer', 'PDFKit'],
      live: 'https://socialmedia-c1dg6ydav-ayush-nemas-projects.vercel.app/dashboard',
      github: 'https://github.com/Ayush-Nema1/Socialmedia',
      featured: true,
    },
    {
      id: 2,
      title: 'Joinfy — Video Conferencing App',
      desc: 'Real-time peer-to-peer video conferencing with live audio/video calling, screen sharing, and real-time chat features. JWT-based authentication for secure meeting rooms.',
      image: '/images/projects/joinfy.png',
      tags: ['WebRTC', 'Socket.io', 'React.js', 'Node.js', 'MongoDB', 'Express.js', 'JWT'],
      live: 'https://videoconfrencing-joinfyfrontend.onrender.com/',
      github: 'https://github.com/Ayush-Nema1/VideoConfrencing-Joinfy-',
    },
    {
      id: 3,
      title: 'WanderLust — Travel Listing App',
      desc: 'Full-stack travel stay listing platform inspired by Airbnb. Create, view, update and delete property listings with RESTful APIs, Joi validation, and responsive Bootstrap UI.',
      image: '/images/projects/wanderlust.png',
      tags: ['Node.js', 'Express.js', 'MongoDB', 'EJS', 'Bootstrap', 'Joi', 'Multer'],
      live: 'https://travel-with-ayush-nema-wunderlust.onrender.com/listings',
      github: 'https://github.com/Ayush-Nema1/Airbnb',
    },
    {
      id: 4,
      title: 'More on GitHub',
      desc: 'I keep building. Check out my GitHub profile for more projects, experiments, and open source contributions.',
      image: null,
      tags: [],
      live: null,
      github: 'https://github.com/Ayush-Nema1',
      githubCard: true,
    },
  ],

  experience: [
    {
      id: 1,
      company: 'Techwalaa',
      role: 'Web Development Intern',
      type: 'Internship',
      mode: 'Remote',
      location: 'Delhi, India',
      duration: 'Feb 2026 – Present',
      period: '2 months',
      current: true,
      desc: 'Building responsive, high-performance web applications using Next.js and React. Contributing to real-world client projects with a focus on clean component architecture, optimised rendering, REST API integration, and cross-browser compatibility.',
      skills: ['Next.js', 'React.js', 'Tailwind CSS', 'Node.js', 'REST APIs', 'Git'],
    },
  ],

  skills: {
    Frontend: [
      { name: 'React.js',     src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
      { name: 'Next.js',      src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg' },
      { name: 'HTML5',        src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg' },
      { name: 'CSS3',         src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg' },
      { name: 'Tailwind CSS', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg' },
      { name: 'Bootstrap',    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg' },
      { name: 'Redux',        src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg' },
    ],
    Backend: [
      { name: 'Node.js',    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
      { name: 'Express.js', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg' },
      { name: 'Socket.io',  src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/socketio/socketio-original.svg' },
      { name: 'WebRTC',     emoji: '📡' },
      { name: 'JWT',        src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jsonwebtokens/jsonwebtokens-original.svg' },
      { name: 'REST APIs',  emoji: '🔗' },
      { name: 'Multer',     emoji: '📁' },
    ],
    Database: [
      { name: 'MongoDB', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg' },
      { name: 'MySQL',   src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg' },
    ],
    Languages: [
      { name: 'JavaScript', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
      { name: 'Java',       src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg' },
      { name: 'C',          src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg' },
      { name: 'SQL',        emoji: '🗃️' },
    ],
    Tools: [
      { name: 'Git',     src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg' },
      { name: 'GitHub',  src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg' },
      { name: 'VS Code', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg' },
      { name: 'Postman', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postman/postman-original.svg' },
    ],
  },

  certifications: [
    {
      id: 1,
      issuer: 'Skyscanner × Forage',
      name: 'Front-End Software Engineering Job Simulation',
      desc: 'Completed practical tasks including building a Backpack React Web App. Issued by Forage on behalf of Skyscanner — November 14, 2025.',
      date: 'November 14, 2025',
      image: '/images/certs/skyscanner.png',
      accent: '#00b4d8',
      badgeBg: '#e0f7fa',
      badgeColor: '#0077a8',
    },
    {
      id: 2,
      issuer: 'Apna College',
      name: 'Alpha — DSA with Java',
      desc: 'Certificate of Completion for successfully completing the Alpha batch — Data Structures & Algorithms with Java, by Shradha Khapra (Co-Founder).',
      date: '01 February 2024',
      image: '/images/certs/dsa.png',
      accent: '#f97316',
      badgeBg: '#fff7ed',
      badgeColor: '#c2410c',
    },
    {
      id: 3,
      issuer: 'NASSCOM · FutureSkills Prime',
      name: 'Digital Application Fundamentals (STEM)',
      desc: 'Certificate of Participation — Digital Application Fundamentals (STEM). Aligned to IT-ITeS Sector Skills Council NASSCOM competency standards. Certificate ID: 26190326361.',
      date: '19 March 2026',
      image: '/images/certs/nasscom.png',
      accent: '#16a34a',
      badgeBg: '#f0fdf4',
      badgeColor: '#15803d',
      certId: '26190326361',
    },
  ],

  education: [
    {
      id: 1,
      institution: 'Baderia Global Engineering College',
      degree: 'Bachelor of Technology — Computer Science & Engineering',
      location: 'Jabalpur, Madhya Pradesh',
      duration: '2023 – 2027',
      current: true,
    },
  ],
}